name: Android build

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64", "armv7" ]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install build-essential flex bison glslang-tools
        sudo apt install meson-1.5 python3-mako python3-markdown

    - name: Build for Android ${{matrix.arch}}
      run: |
        echo "Building on: ${{ matrix.arch }}"
        export MATRIX_ARCH="${{ matrix.arch }}"
        pushd build-android
        bash ./build_${{ matrix.arch }}.sh
        popd

    - name: Compress artifacts
      run: |
        pushd /tmp/zink-${{matrix.arch}}/lib
        rm libEGL_legacy.so libglapi.so
        mv libEGL_legacy.so.1.0.0 libEGL_legacy.so
        mv libglapi.so.0.0.0 libglapi.so
        mv dri/zink_dri.so .
        zip -j "$OLDPWD/mesa-${{matrix.arch}}.zip" libEGL_legacy.so libdrm.so zink_dri.so libglapi.so || true;
        popd
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mesa-${{ matrix.arch }}
        path: ./mesa-${{ matrix.arch }}.zip

